/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_appsync_graphqlEndpoint:
    'https://trjc7ievpzgmbljg7cbtv2772e.appsync-api.us-east-1.amazonaws.com/graphql',
  aws_appsync_region: 'us-east-1',
  aws_appsync_authenticationType: 'API_KEY',
  aws_appsync_apiKey: 'da2-24eqpys2vfgude7ytrlk7erccm',
  aws_cognito_identity_pool_id:
    'us-east-1:0b659666-91e0-4546-b90e-996b55ac0c72',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_KnmJMqUbH',
  aws_user_pools_web_client_id: '4o9fqkhirb9n5ddogcvkrc85s4',
  oauth: {},
  aws_cognito_username_attributes: [],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ['EMAIL'],
  aws_cognito_mfa_configuration: 'OFF',
  aws_cognito_mfa_types: ['SMS'],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ['EMAIL'],
  aws_content_delivery_bucket: 'hassannazir-20221116211954-hostingbucket-dev',
  aws_content_delivery_bucket_region: 'us-east-1',
  aws_content_delivery_url:
    'http://hassannazir-20221116211954-hostingbucket-dev.s3-website-us-east-1.amazonaws.com',
};

export default awsmobile;
